### ISSUE TITLE
how to generate docset using this repo?

### ISSUE THREAD

**Issue by googya** [alexbepple/ramda-dash-docset#14]
should i use "make builder" , does it need Docker?

**Comment by alexbepple** [comment]
Yes, it needs Docker. Docker should be the only requirement. Everything else should happen in the image/container.

Like the README says, `make builder` to create the Docker image that is used to run the actual build. Then `make` to generate the docset. It will be in `build-default/`. You can `make install` to add the built docset to Dash.
