### ISSUE TITLE
v0.27.0?

### ISSUE THREAD

**Issue by mikestopcontinues** [alexbepple/ramda-dash-docset#19]
@alexbepple : Thanks a million! I don't think I would've had as easy a time with Ramda without your docset. Any chance for a 0.27.0 version? Or a ramda-adjunct docset?

**Comment by alexbepple** [comment]
The official site https://ramdajs.com/ doesn't have 0.27 yet.
The docset generation relies on the official docs and their availability at https://github.com/ramda/ramda.github.io. So, I don't see a simple way to do this. Also, something seems off with 0.27. There isn't even a changelog/upgrade guide yet, cp. https://github.com/ramda/ramda/issues?q=label%3A%22upgrade+guide%22

**Comment by mikestopcontinues** [comment]
I noticed that later, but strangely, 0.27.0 is what gets installed via NPM. I'm going to open an issue with them. Thanks for looking into it!

**Comment by mikestopcontinues** [comment]
Hey, it looks like the docs are updated. Everything good to go?

**Comment by alexbepple** [comment]
Thanks for the update. I’ll take a look this weekend.

**Comment by alexbepple** [comment]
Has been published earlier today. Sorry that it took me so long.

**Comment by mikestopcontinues** [comment]
🚀 Thanks!
