### ISSUE TITLE
Ramda Docs are outdated

### ISSUE THREAD

**Issue by jeffhoelter** [alexbepple/ramda-dash-docset#3]
0.13 is the latest available in your repo, but 0.15 is out on Ramda's github site.

I hacked your script up and made my own Ramda docs for Dash, but it wasn't pretty. :)

**Comment by alexbepple** [comment]
@jeffhoelter, I will get around to this at the end of the week.

**Comment by alexbepple** [comment]
Getting around to it right now.

**Comment by alexbepple** [comment]
cp Kapeli/Dash-User-Contributions/pull/571

**Comment by alexbepple** [comment]
cp Kapeli/Dash-User-Contributions/pull/571
