### ISSUE TITLE
make prod error

### ISSUE THREAD

**Issue by jasonHzq** [alexbepple/ramda-dash-docset#5]
mkdir -p build/Ramda.docset
cp -R static/\* build/Ramda.docset
ditto vendor/ramdajs.com/0.17/style.css build/Ramda.docset/Contents/Resources/Documents/style.css
ditto: can't get real path for source 'vendor/ramdajs.com/0.17/style.css'
make: **\* [style.css] Error 1
can't get real path for source 'vendor/ramdajs.com/0.17/style.css

**Comment by zhangchiqing** [comment]
same here

**Comment by alexbepple** [comment]
Does this persist with the recent switch to peru? cp 24211b93020454c1038f1c862aadd5646f40ddce
And perhaps a clean clone?

**Comment by zhangchiqing** [comment]
It works for me now. :+1:

**Comment by alexbepple** [comment]
:+1:
