### ISSUE TITLE
Enable `Try in REPL`

### ISSUE THREAD

**Issue by datenreisender** [alexbepple/ramda-dash-docset#9]
The `Try in REPL` within the code snippets currently either does nothing (when clicked on in Dash) or are broken links (when clicked on a local page like [http://localhost:56733/Dash/colbtnvp/docs/index.html#compose](http://localhost:56733/Dash/colbtnvp/docs/index.html#compose)).

**Comment by alexbepple** [comment]
Closed by 3e201fbf818b2baa4e06dfe1539561b56fbbe8cc
